<?php
/**
 * InstagramApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zernio\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Zernio\ApiException;
use Zernio\Configuration;
use Zernio\FormDataProcessor;
use Zernio\HeaderSelector;
use Zernio\ObjectSerializer;

/**
 * InstagramApi Class Doc Comment
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstagramApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getInstagramAudio' => [
            'application/json',
        ],
        'getInstagramPublishingLimit' => [
            'application/json',
        ],
        'getInstagramStoryInsights' => [
            'application/json',
        ],
        'listInstagramStories' => [
            'application/json',
        ],
        'searchInstagramAudio' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getInstagramAudio
     *
     * Get Instagram audio metadata
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_id Instagram audio asset ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramAudio'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zernio\Model\GetInstagramAudio200Response|\Zernio\Model\ErrorResponse|\Zernio\Model\InlineObject1
     */
    public function getInstagramAudio($account_id, $audio_id, string $contentType = self::contentTypes['getInstagramAudio'][0])
    {
        list($response) = $this->getInstagramAudioWithHttpInfo($account_id, $audio_id, $contentType);
        return $response;
    }

    /**
     * Operation getInstagramAudioWithHttpInfo
     *
     * Get Instagram audio metadata
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_id Instagram audio asset ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramAudio'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zernio\Model\GetInstagramAudio200Response|\Zernio\Model\ErrorResponse|\Zernio\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInstagramAudioWithHttpInfo($account_id, $audio_id, string $contentType = self::contentTypes['getInstagramAudio'][0])
    {
        $request = $this->getInstagramAudioRequest($account_id, $audio_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\GetInstagramAudio200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zernio\Model\GetInstagramAudio200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\GetInstagramAudio200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInstagramAudioAsync
     *
     * Get Instagram audio metadata
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_id Instagram audio asset ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramAudioAsync($account_id, $audio_id, string $contentType = self::contentTypes['getInstagramAudio'][0])
    {
        return $this->getInstagramAudioAsyncWithHttpInfo($account_id, $audio_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInstagramAudioAsyncWithHttpInfo
     *
     * Get Instagram audio metadata
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_id Instagram audio asset ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramAudioAsyncWithHttpInfo($account_id, $audio_id, string $contentType = self::contentTypes['getInstagramAudio'][0])
    {
        $returnType = '\Zernio\Model\GetInstagramAudio200Response';
        $request = $this->getInstagramAudioRequest($account_id, $audio_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInstagramAudio'
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_id Instagram audio asset ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInstagramAudioRequest($account_id, $audio_id, string $contentType = self::contentTypes['getInstagramAudio'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getInstagramAudio'
            );
        }

        // verify the required parameter 'audio_id' is set
        if ($audio_id === null || (is_array($audio_id) && count($audio_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $audio_id when calling getInstagramAudio'
            );
        }
        if (!preg_match("/^\\d{1,30}$/", $audio_id)) {
            throw new \InvalidArgumentException("invalid value for \"audio_id\" when calling InstagramApi.getInstagramAudio, must conform to the pattern /^\\d{1,30}$/.");
        }
        

        $resourcePath = '/v1/accounts/{accountId}/instagram/audio/{audioId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($audio_id !== null) {
            $resourcePath = str_replace(
                '{' . 'audioId' . '}',
                ObjectSerializer::toPathValue($audio_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getInstagramPublishingLimit
     *
     * Get Instagram publishing limit
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramPublishingLimit'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zernio\Model\GetInstagramPublishingLimit200Response|\Zernio\Model\InlineObject1
     */
    public function getInstagramPublishingLimit($account_id, string $contentType = self::contentTypes['getInstagramPublishingLimit'][0])
    {
        list($response) = $this->getInstagramPublishingLimitWithHttpInfo($account_id, $contentType);
        return $response;
    }

    /**
     * Operation getInstagramPublishingLimitWithHttpInfo
     *
     * Get Instagram publishing limit
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramPublishingLimit'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zernio\Model\GetInstagramPublishingLimit200Response|\Zernio\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInstagramPublishingLimitWithHttpInfo($account_id, string $contentType = self::contentTypes['getInstagramPublishingLimit'][0])
    {
        $request = $this->getInstagramPublishingLimitRequest($account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\GetInstagramPublishingLimit200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zernio\Model\GetInstagramPublishingLimit200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\GetInstagramPublishingLimit200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInstagramPublishingLimitAsync
     *
     * Get Instagram publishing limit
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramPublishingLimit'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramPublishingLimitAsync($account_id, string $contentType = self::contentTypes['getInstagramPublishingLimit'][0])
    {
        return $this->getInstagramPublishingLimitAsyncWithHttpInfo($account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInstagramPublishingLimitAsyncWithHttpInfo
     *
     * Get Instagram publishing limit
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramPublishingLimit'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramPublishingLimitAsyncWithHttpInfo($account_id, string $contentType = self::contentTypes['getInstagramPublishingLimit'][0])
    {
        $returnType = '\Zernio\Model\GetInstagramPublishingLimit200Response';
        $request = $this->getInstagramPublishingLimitRequest($account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInstagramPublishingLimit'
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramPublishingLimit'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInstagramPublishingLimitRequest($account_id, string $contentType = self::contentTypes['getInstagramPublishingLimit'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getInstagramPublishingLimit'
            );
        }


        $resourcePath = '/v1/accounts/{accountId}/instagram/publishing-limit';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getInstagramStoryInsights
     *
     * Get Instagram story insights
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $story_id The Instagram media ID of the story. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramStoryInsights'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zernio\Model\GetInstagramStoryInsights200Response|\Zernio\Model\InlineObject1
     */
    public function getInstagramStoryInsights($account_id, $story_id, string $contentType = self::contentTypes['getInstagramStoryInsights'][0])
    {
        list($response) = $this->getInstagramStoryInsightsWithHttpInfo($account_id, $story_id, $contentType);
        return $response;
    }

    /**
     * Operation getInstagramStoryInsightsWithHttpInfo
     *
     * Get Instagram story insights
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $story_id The Instagram media ID of the story. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramStoryInsights'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zernio\Model\GetInstagramStoryInsights200Response|\Zernio\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInstagramStoryInsightsWithHttpInfo($account_id, $story_id, string $contentType = self::contentTypes['getInstagramStoryInsights'][0])
    {
        $request = $this->getInstagramStoryInsightsRequest($account_id, $story_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\GetInstagramStoryInsights200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zernio\Model\GetInstagramStoryInsights200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\GetInstagramStoryInsights200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInstagramStoryInsightsAsync
     *
     * Get Instagram story insights
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $story_id The Instagram media ID of the story. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramStoryInsights'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramStoryInsightsAsync($account_id, $story_id, string $contentType = self::contentTypes['getInstagramStoryInsights'][0])
    {
        return $this->getInstagramStoryInsightsAsyncWithHttpInfo($account_id, $story_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInstagramStoryInsightsAsyncWithHttpInfo
     *
     * Get Instagram story insights
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $story_id The Instagram media ID of the story. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramStoryInsights'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstagramStoryInsightsAsyncWithHttpInfo($account_id, $story_id, string $contentType = self::contentTypes['getInstagramStoryInsights'][0])
    {
        $returnType = '\Zernio\Model\GetInstagramStoryInsights200Response';
        $request = $this->getInstagramStoryInsightsRequest($account_id, $story_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInstagramStoryInsights'
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $story_id The Instagram media ID of the story. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstagramStoryInsights'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInstagramStoryInsightsRequest($account_id, $story_id, string $contentType = self::contentTypes['getInstagramStoryInsights'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getInstagramStoryInsights'
            );
        }

        // verify the required parameter 'story_id' is set
        if ($story_id === null || (is_array($story_id) && count($story_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $story_id when calling getInstagramStoryInsights'
            );
        }


        $resourcePath = '/v1/accounts/{accountId}/instagram/stories/{storyId}/insights';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($story_id !== null) {
            $resourcePath = str_replace(
                '{' . 'storyId' . '}',
                ObjectSerializer::toPathValue($story_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listInstagramStories
     *
     * List active Instagram stories
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listInstagramStories'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zernio\Model\ListInstagramStories200Response|\Zernio\Model\InlineObject1
     */
    public function listInstagramStories($account_id, string $contentType = self::contentTypes['listInstagramStories'][0])
    {
        list($response) = $this->listInstagramStoriesWithHttpInfo($account_id, $contentType);
        return $response;
    }

    /**
     * Operation listInstagramStoriesWithHttpInfo
     *
     * List active Instagram stories
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listInstagramStories'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zernio\Model\ListInstagramStories200Response|\Zernio\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function listInstagramStoriesWithHttpInfo($account_id, string $contentType = self::contentTypes['listInstagramStories'][0])
    {
        $request = $this->listInstagramStoriesRequest($account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\ListInstagramStories200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zernio\Model\ListInstagramStories200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\ListInstagramStories200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listInstagramStoriesAsync
     *
     * List active Instagram stories
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listInstagramStories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listInstagramStoriesAsync($account_id, string $contentType = self::contentTypes['listInstagramStories'][0])
    {
        return $this->listInstagramStoriesAsyncWithHttpInfo($account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listInstagramStoriesAsyncWithHttpInfo
     *
     * List active Instagram stories
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listInstagramStories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listInstagramStoriesAsyncWithHttpInfo($account_id, string $contentType = self::contentTypes['listInstagramStories'][0])
    {
        $returnType = '\Zernio\Model\ListInstagramStories200Response';
        $request = $this->listInstagramStoriesRequest($account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listInstagramStories'
     *
     * @param  string $account_id The Instagram account ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listInstagramStories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listInstagramStoriesRequest($account_id, string $contentType = self::contentTypes['listInstagramStories'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling listInstagramStories'
            );
        }


        $resourcePath = '/v1/accounts/{accountId}/instagram/stories';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchInstagramAudio
     *
     * Search Instagram audio
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_type Catalog to search: licensed music or original sounds from Reels. (required)
     * @param  string|null $q Search keywords. Omit to get the current trending list. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchInstagramAudio'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Zernio\Model\SearchInstagramAudio200Response|\Zernio\Model\ErrorResponse|\Zernio\Model\InlineObject1
     */
    public function searchInstagramAudio($account_id, $audio_type, $q = null, string $contentType = self::contentTypes['searchInstagramAudio'][0])
    {
        list($response) = $this->searchInstagramAudioWithHttpInfo($account_id, $audio_type, $q, $contentType);
        return $response;
    }

    /**
     * Operation searchInstagramAudioWithHttpInfo
     *
     * Search Instagram audio
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_type Catalog to search: licensed music or original sounds from Reels. (required)
     * @param  string|null $q Search keywords. Omit to get the current trending list. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchInstagramAudio'] to see the possible values for this operation
     *
     * @throws \Zernio\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Zernio\Model\SearchInstagramAudio200Response|\Zernio\Model\ErrorResponse|\Zernio\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchInstagramAudioWithHttpInfo($account_id, $audio_type, $q = null, string $contentType = self::contentTypes['searchInstagramAudio'][0])
    {
        $request = $this->searchInstagramAudioRequest($account_id, $audio_type, $q, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\SearchInstagramAudio200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Zernio\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Zernio\Model\SearchInstagramAudio200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\SearchInstagramAudio200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Zernio\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchInstagramAudioAsync
     *
     * Search Instagram audio
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_type Catalog to search: licensed music or original sounds from Reels. (required)
     * @param  string|null $q Search keywords. Omit to get the current trending list. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchInstagramAudioAsync($account_id, $audio_type, $q = null, string $contentType = self::contentTypes['searchInstagramAudio'][0])
    {
        return $this->searchInstagramAudioAsyncWithHttpInfo($account_id, $audio_type, $q, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchInstagramAudioAsyncWithHttpInfo
     *
     * Search Instagram audio
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_type Catalog to search: licensed music or original sounds from Reels. (required)
     * @param  string|null $q Search keywords. Omit to get the current trending list. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchInstagramAudioAsyncWithHttpInfo($account_id, $audio_type, $q = null, string $contentType = self::contentTypes['searchInstagramAudio'][0])
    {
        $returnType = '\Zernio\Model\SearchInstagramAudio200Response';
        $request = $this->searchInstagramAudioRequest($account_id, $audio_type, $q, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchInstagramAudio'
     *
     * @param  string $account_id The ID of the Instagram account (required)
     * @param  string $audio_type Catalog to search: licensed music or original sounds from Reels. (required)
     * @param  string|null $q Search keywords. Omit to get the current trending list. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchInstagramAudio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchInstagramAudioRequest($account_id, $audio_type, $q = null, string $contentType = self::contentTypes['searchInstagramAudio'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling searchInstagramAudio'
            );
        }

        // verify the required parameter 'audio_type' is set
        if ($audio_type === null || (is_array($audio_type) && count($audio_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $audio_type when calling searchInstagramAudio'
            );
        }

        if ($q !== null && strlen($q) > 200) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling InstagramApi.searchInstagramAudio, must be smaller than or equal to 200.');
        }
        if ($q !== null && strlen($q) < 1) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling InstagramApi.searchInstagramAudio, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/accounts/{accountId}/instagram/audio';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $audio_type,
            'audioType', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
