<?php
/**
 * AdActivationStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.217.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zernio\Model;
use \Zernio\ObjectSerializer;

/**
 * AdActivationStatus Class Doc Comment
 *
 * @category Class
 * @description Request-side publish switch for &#x60;adStatus&#x60; on ad creation endpoints only (&#x60;status&#x60;, &#x60;campaignStatus&#x60; and &#x60;adSetStatus&#x60; carry their own inline ACTIVE/PAUSED enum there; the status-update endpoints are a separate lowercase &#x60;active&#x60;/&#x60;paused&#x60; enum). Distinct from &#x60;AdStatus&#x60; (the platform-reported delivery status returned on reads).
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdActivationStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'ACTIVE';

    public const PAUSED = 'PAUSED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::PAUSED
        ];
    }
}


