<?php
/**
 * GetCampaignConversionGoals200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.128.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zernio\Model;

use \ArrayAccess;
use \Zernio\ObjectSerializer;

/**
 * GetCampaignConversionGoals200Response Class Doc Comment
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetCampaignConversionGoals200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getCampaignConversionGoals_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'campaign_id' => 'string',
        'goal_config_level' => 'string',
        'custom_conversion_goal_id' => 'string',
        'goals' => '\Zernio\Model\GoogleCampaignConversionGoalsGoalsInner[]',
        'customer_id' => 'string',
        'cached_at' => '\DateTime',
        'stale' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'campaign_id' => null,
        'goal_config_level' => null,
        'custom_conversion_goal_id' => null,
        'goals' => null,
        'customer_id' => null,
        'cached_at' => 'date-time',
        'stale' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'campaign_id' => false,
        'goal_config_level' => false,
        'custom_conversion_goal_id' => false,
        'goals' => false,
        'customer_id' => false,
        'cached_at' => true,
        'stale' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'campaign_id' => 'campaignId',
        'goal_config_level' => 'goalConfigLevel',
        'custom_conversion_goal_id' => 'customConversionGoalId',
        'goals' => 'goals',
        'customer_id' => 'customerId',
        'cached_at' => 'cachedAt',
        'stale' => 'stale'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'campaign_id' => 'setCampaignId',
        'goal_config_level' => 'setGoalConfigLevel',
        'custom_conversion_goal_id' => 'setCustomConversionGoalId',
        'goals' => 'setGoals',
        'customer_id' => 'setCustomerId',
        'cached_at' => 'setCachedAt',
        'stale' => 'setStale'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'campaign_id' => 'getCampaignId',
        'goal_config_level' => 'getGoalConfigLevel',
        'custom_conversion_goal_id' => 'getCustomConversionGoalId',
        'goals' => 'getGoals',
        'customer_id' => 'getCustomerId',
        'cached_at' => 'getCachedAt',
        'stale' => 'getStale'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const GOAL_CONFIG_LEVEL_CUSTOMER = 'CUSTOMER';
    public const GOAL_CONFIG_LEVEL_CAMPAIGN = 'CAMPAIGN';
    public const GOAL_CONFIG_LEVEL_UNSPECIFIED = 'UNSPECIFIED';
    public const GOAL_CONFIG_LEVEL_UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGoalConfigLevelAllowableValues()
    {
        return [
            self::GOAL_CONFIG_LEVEL_CUSTOMER,
            self::GOAL_CONFIG_LEVEL_CAMPAIGN,
            self::GOAL_CONFIG_LEVEL_UNSPECIFIED,
            self::GOAL_CONFIG_LEVEL_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('campaign_id', $data ?? [], null);
        $this->setIfExists('goal_config_level', $data ?? [], null);
        $this->setIfExists('custom_conversion_goal_id', $data ?? [], null);
        $this->setIfExists('goals', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('cached_at', $data ?? [], null);
        $this->setIfExists('stale', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getGoalConfigLevelAllowableValues();
        if (!is_null($this->container['goal_config_level']) && !in_array($this->container['goal_config_level'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'goal_config_level', must be one of '%s'",
                $this->container['goal_config_level'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets campaign_id
     *
     * @return string|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param string|null $campaign_id campaign_id
     *
     * @return self
     */
    public function setCampaignId($campaign_id)
    {
        if (is_null($campaign_id)) {
            throw new \InvalidArgumentException('non-nullable campaign_id cannot be null');
        }
        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets goal_config_level
     *
     * @return string|null
     */
    public function getGoalConfigLevel()
    {
        return $this->container['goal_config_level'];
    }

    /**
     * Sets goal_config_level
     *
     * @param string|null $goal_config_level goal_config_level
     *
     * @return self
     */
    public function setGoalConfigLevel($goal_config_level)
    {
        if (is_null($goal_config_level)) {
            throw new \InvalidArgumentException('non-nullable goal_config_level cannot be null');
        }
        $allowedValues = $this->getGoalConfigLevelAllowableValues();
        if (!in_array($goal_config_level, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'goal_config_level', must be one of '%s'",
                    $goal_config_level,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['goal_config_level'] = $goal_config_level;

        return $this;
    }

    /**
     * Gets custom_conversion_goal_id
     *
     * @return string|null
     */
    public function getCustomConversionGoalId()
    {
        return $this->container['custom_conversion_goal_id'];
    }

    /**
     * Sets custom_conversion_goal_id
     *
     * @param string|null $custom_conversion_goal_id custom_conversion_goal_id
     *
     * @return self
     */
    public function setCustomConversionGoalId($custom_conversion_goal_id)
    {
        if (is_null($custom_conversion_goal_id)) {
            throw new \InvalidArgumentException('non-nullable custom_conversion_goal_id cannot be null');
        }
        $this->container['custom_conversion_goal_id'] = $custom_conversion_goal_id;

        return $this;
    }

    /**
     * Gets goals
     *
     * @return \Zernio\Model\GoogleCampaignConversionGoalsGoalsInner[]|null
     */
    public function getGoals()
    {
        return $this->container['goals'];
    }

    /**
     * Sets goals
     *
     * @param \Zernio\Model\GoogleCampaignConversionGoalsGoalsInner[]|null $goals goals
     *
     * @return self
     */
    public function setGoals($goals)
    {
        if (is_null($goals)) {
            throw new \InvalidArgumentException('non-nullable goals cannot be null');
        }
        $this->container['goals'] = $goals;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id customer_id
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            throw new \InvalidArgumentException('non-nullable customer_id cannot be null');
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets cached_at
     *
     * @return \DateTime|null
     */
    public function getCachedAt()
    {
        return $this->container['cached_at'];
    }

    /**
     * Sets cached_at
     *
     * @param \DateTime|null $cached_at cached_at
     *
     * @return self
     */
    public function setCachedAt($cached_at)
    {
        if (is_null($cached_at)) {
            array_push($this->openAPINullablesSetToNull, 'cached_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cached_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cached_at'] = $cached_at;

        return $this;
    }

    /**
     * Gets stale
     *
     * @return bool|null
     */
    public function getStale()
    {
        return $this->container['stale'];
    }

    /**
     * Sets stale
     *
     * @param bool|null $stale stale
     *
     * @return self
     */
    public function setStale($stale)
    {
        if (is_null($stale)) {
            throw new \InvalidArgumentException('non-nullable stale cannot be null');
        }
        $this->container['stale'] = $stale;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


