<?php
/**
 * GetInstagramStoryInsights200ResponseDataMetrics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zernio\Model;

use \ArrayAccess;
use \Zernio\ObjectSerializer;

/**
 * GetInstagramStoryInsights200ResponseDataMetrics Class Doc Comment
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetInstagramStoryInsights200ResponseDataMetrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getInstagramStoryInsights_200_response_data_metrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'views' => 'int',
        'reach' => 'int',
        'replies' => 'int',
        'shares' => 'int',
        'navigation' => 'int',
        'taps_forward' => 'int',
        'taps_back' => 'int',
        'exits' => 'int',
        'swipes_forward' => 'int',
        'profile_visits' => 'int',
        'follows' => 'int',
        'reposts' => 'int',
        'total_interactions' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'views' => null,
        'reach' => null,
        'replies' => null,
        'shares' => null,
        'navigation' => null,
        'taps_forward' => null,
        'taps_back' => null,
        'exits' => null,
        'swipes_forward' => null,
        'profile_visits' => null,
        'follows' => null,
        'reposts' => null,
        'total_interactions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'views' => false,
        'reach' => false,
        'replies' => false,
        'shares' => false,
        'navigation' => false,
        'taps_forward' => false,
        'taps_back' => false,
        'exits' => false,
        'swipes_forward' => false,
        'profile_visits' => false,
        'follows' => false,
        'reposts' => false,
        'total_interactions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'views' => 'views',
        'reach' => 'reach',
        'replies' => 'replies',
        'shares' => 'shares',
        'navigation' => 'navigation',
        'taps_forward' => 'tapsForward',
        'taps_back' => 'tapsBack',
        'exits' => 'exits',
        'swipes_forward' => 'swipesForward',
        'profile_visits' => 'profileVisits',
        'follows' => 'follows',
        'reposts' => 'reposts',
        'total_interactions' => 'totalInteractions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'views' => 'setViews',
        'reach' => 'setReach',
        'replies' => 'setReplies',
        'shares' => 'setShares',
        'navigation' => 'setNavigation',
        'taps_forward' => 'setTapsForward',
        'taps_back' => 'setTapsBack',
        'exits' => 'setExits',
        'swipes_forward' => 'setSwipesForward',
        'profile_visits' => 'setProfileVisits',
        'follows' => 'setFollows',
        'reposts' => 'setReposts',
        'total_interactions' => 'setTotalInteractions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'views' => 'getViews',
        'reach' => 'getReach',
        'replies' => 'getReplies',
        'shares' => 'getShares',
        'navigation' => 'getNavigation',
        'taps_forward' => 'getTapsForward',
        'taps_back' => 'getTapsBack',
        'exits' => 'getExits',
        'swipes_forward' => 'getSwipesForward',
        'profile_visits' => 'getProfileVisits',
        'follows' => 'getFollows',
        'reposts' => 'getReposts',
        'total_interactions' => 'getTotalInteractions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('views', $data ?? [], null);
        $this->setIfExists('reach', $data ?? [], null);
        $this->setIfExists('replies', $data ?? [], null);
        $this->setIfExists('shares', $data ?? [], null);
        $this->setIfExists('navigation', $data ?? [], null);
        $this->setIfExists('taps_forward', $data ?? [], null);
        $this->setIfExists('taps_back', $data ?? [], null);
        $this->setIfExists('exits', $data ?? [], null);
        $this->setIfExists('swipes_forward', $data ?? [], null);
        $this->setIfExists('profile_visits', $data ?? [], null);
        $this->setIfExists('follows', $data ?? [], null);
        $this->setIfExists('reposts', $data ?? [], null);
        $this->setIfExists('total_interactions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['views'] === null) {
            $invalidProperties[] = "'views' can't be null";
        }
        if ($this->container['reach'] === null) {
            $invalidProperties[] = "'reach' can't be null";
        }
        if ($this->container['replies'] === null) {
            $invalidProperties[] = "'replies' can't be null";
        }
        if ($this->container['shares'] === null) {
            $invalidProperties[] = "'shares' can't be null";
        }
        if ($this->container['navigation'] === null) {
            $invalidProperties[] = "'navigation' can't be null";
        }
        if ($this->container['taps_forward'] === null) {
            $invalidProperties[] = "'taps_forward' can't be null";
        }
        if ($this->container['taps_back'] === null) {
            $invalidProperties[] = "'taps_back' can't be null";
        }
        if ($this->container['exits'] === null) {
            $invalidProperties[] = "'exits' can't be null";
        }
        if ($this->container['swipes_forward'] === null) {
            $invalidProperties[] = "'swipes_forward' can't be null";
        }
        if ($this->container['profile_visits'] === null) {
            $invalidProperties[] = "'profile_visits' can't be null";
        }
        if ($this->container['follows'] === null) {
            $invalidProperties[] = "'follows' can't be null";
        }
        if ($this->container['reposts'] === null) {
            $invalidProperties[] = "'reposts' can't be null";
        }
        if ($this->container['total_interactions'] === null) {
            $invalidProperties[] = "'total_interactions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets views
     *
     * @return int
     */
    public function getViews()
    {
        return $this->container['views'];
    }

    /**
     * Sets views
     *
     * @param int $views Total story plays. Replaces deprecated 'impressions' for media created after 2024-07-02.
     *
     * @return self
     */
    public function setViews($views)
    {
        if (is_null($views)) {
            throw new \InvalidArgumentException('non-nullable views cannot be null');
        }
        $this->container['views'] = $views;

        return $this;
    }

    /**
     * Gets reach
     *
     * @return int
     */
    public function getReach()
    {
        return $this->container['reach'];
    }

    /**
     * Sets reach
     *
     * @param int $reach Unique accounts that saw the story.
     *
     * @return self
     */
    public function setReach($reach)
    {
        if (is_null($reach)) {
            throw new \InvalidArgumentException('non-nullable reach cannot be null');
        }
        $this->container['reach'] = $reach;

        return $this;
    }

    /**
     * Gets replies
     *
     * @return int
     */
    public function getReplies()
    {
        return $this->container['replies'];
    }

    /**
     * Sets replies
     *
     * @param int $replies DMs sent in reply to the story.
     *
     * @return self
     */
    public function setReplies($replies)
    {
        if (is_null($replies)) {
            throw new \InvalidArgumentException('non-nullable replies cannot be null');
        }
        $this->container['replies'] = $replies;

        return $this;
    }

    /**
     * Gets shares
     *
     * @return int
     */
    public function getShares()
    {
        return $this->container['shares'];
    }

    /**
     * Sets shares
     *
     * @param int $shares shares
     *
     * @return self
     */
    public function setShares($shares)
    {
        if (is_null($shares)) {
            throw new \InvalidArgumentException('non-nullable shares cannot be null');
        }
        $this->container['shares'] = $shares;

        return $this;
    }

    /**
     * Gets navigation
     *
     * @return int
     */
    public function getNavigation()
    {
        return $this->container['navigation'];
    }

    /**
     * Sets navigation
     *
     * @param int $navigation Total nav actions (tapsForward + tapsBack + exits + swipesForward).
     *
     * @return self
     */
    public function setNavigation($navigation)
    {
        if (is_null($navigation)) {
            throw new \InvalidArgumentException('non-nullable navigation cannot be null');
        }
        $this->container['navigation'] = $navigation;

        return $this;
    }

    /**
     * Gets taps_forward
     *
     * @return int
     */
    public function getTapsForward()
    {
        return $this->container['taps_forward'];
    }

    /**
     * Sets taps_forward
     *
     * @param int $taps_forward Tapped right to next slide of SAME story.
     *
     * @return self
     */
    public function setTapsForward($taps_forward)
    {
        if (is_null($taps_forward)) {
            throw new \InvalidArgumentException('non-nullable taps_forward cannot be null');
        }
        $this->container['taps_forward'] = $taps_forward;

        return $this;
    }

    /**
     * Gets taps_back
     *
     * @return int
     */
    public function getTapsBack()
    {
        return $this->container['taps_back'];
    }

    /**
     * Sets taps_back
     *
     * @param int $taps_back Tapped left to previous slide.
     *
     * @return self
     */
    public function setTapsBack($taps_back)
    {
        if (is_null($taps_back)) {
            throw new \InvalidArgumentException('non-nullable taps_back cannot be null');
        }
        $this->container['taps_back'] = $taps_back;

        return $this;
    }

    /**
     * Gets exits
     *
     * @return int
     */
    public function getExits()
    {
        return $this->container['exits'];
    }

    /**
     * Sets exits
     *
     * @param int $exits Closed Stories interface entirely.
     *
     * @return self
     */
    public function setExits($exits)
    {
        if (is_null($exits)) {
            throw new \InvalidArgumentException('non-nullable exits cannot be null');
        }
        $this->container['exits'] = $exits;

        return $this;
    }

    /**
     * Gets swipes_forward
     *
     * @return int
     */
    public function getSwipesForward()
    {
        return $this->container['swipes_forward'];
    }

    /**
     * Sets swipes_forward
     *
     * @param int $swipes_forward Swiped left to next account's story.
     *
     * @return self
     */
    public function setSwipesForward($swipes_forward)
    {
        if (is_null($swipes_forward)) {
            throw new \InvalidArgumentException('non-nullable swipes_forward cannot be null');
        }
        $this->container['swipes_forward'] = $swipes_forward;

        return $this;
    }

    /**
     * Gets profile_visits
     *
     * @return int
     */
    public function getProfileVisits()
    {
        return $this->container['profile_visits'];
    }

    /**
     * Sets profile_visits
     *
     * @param int $profile_visits profile_visits
     *
     * @return self
     */
    public function setProfileVisits($profile_visits)
    {
        if (is_null($profile_visits)) {
            throw new \InvalidArgumentException('non-nullable profile_visits cannot be null');
        }
        $this->container['profile_visits'] = $profile_visits;

        return $this;
    }

    /**
     * Gets follows
     *
     * @return int
     */
    public function getFollows()
    {
        return $this->container['follows'];
    }

    /**
     * Sets follows
     *
     * @param int $follows follows
     *
     * @return self
     */
    public function setFollows($follows)
    {
        if (is_null($follows)) {
            throw new \InvalidArgumentException('non-nullable follows cannot be null');
        }
        $this->container['follows'] = $follows;

        return $this;
    }

    /**
     * Gets reposts
     *
     * @return int
     */
    public function getReposts()
    {
        return $this->container['reposts'];
    }

    /**
     * Sets reposts
     *
     * @param int $reposts reposts
     *
     * @return self
     */
    public function setReposts($reposts)
    {
        if (is_null($reposts)) {
            throw new \InvalidArgumentException('non-nullable reposts cannot be null');
        }
        $this->container['reposts'] = $reposts;

        return $this;
    }

    /**
     * Gets total_interactions
     *
     * @return int
     */
    public function getTotalInteractions()
    {
        return $this->container['total_interactions'];
    }

    /**
     * Sets total_interactions
     *
     * @param int $total_interactions total_interactions
     *
     * @return self
     */
    public function setTotalInteractions($total_interactions)
    {
        if (is_null($total_interactions)) {
            throw new \InvalidArgumentException('non-nullable total_interactions cannot be null');
        }
        $this->container['total_interactions'] = $total_interactions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


