<?php
/**
 * GetInboxPostComments200ResponseCommentsInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Late\Model;

use \ArrayAccess;
use \Late\ObjectSerializer;

/**
 * GetInboxPostComments200ResponseCommentsInner Class Doc Comment
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetInboxPostComments200ResponseCommentsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getInboxPostComments_200_response_comments_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'message' => 'string',
        'created_time' => '\DateTime',
        'from' => '\Late\Model\GetInboxPostComments200ResponseCommentsInnerFrom',
        'like_count' => 'int',
        'reply_count' => 'int',
        'platform' => 'string',
        'url' => 'string',
        'replies' => 'object[]',
        'can_reply' => 'bool',
        'can_delete' => 'bool',
        'can_hide' => 'bool',
        'can_like' => 'bool',
        'is_hidden' => 'bool',
        'is_liked' => 'bool',
        'like_uri' => 'string',
        'cid' => 'string',
        'parent_id' => 'string',
        'root_uri' => 'string',
        'root_cid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'message' => null,
        'created_time' => 'date-time',
        'from' => null,
        'like_count' => null,
        'reply_count' => null,
        'platform' => null,
        'url' => null,
        'replies' => null,
        'can_reply' => null,
        'can_delete' => null,
        'can_hide' => null,
        'can_like' => null,
        'is_hidden' => null,
        'is_liked' => null,
        'like_uri' => null,
        'cid' => null,
        'parent_id' => null,
        'root_uri' => null,
        'root_cid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'message' => false,
        'created_time' => false,
        'from' => false,
        'like_count' => false,
        'reply_count' => false,
        'platform' => false,
        'url' => false,
        'replies' => false,
        'can_reply' => false,
        'can_delete' => false,
        'can_hide' => false,
        'can_like' => false,
        'is_hidden' => false,
        'is_liked' => false,
        'like_uri' => false,
        'cid' => false,
        'parent_id' => false,
        'root_uri' => false,
        'root_cid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'message' => 'message',
        'created_time' => 'createdTime',
        'from' => 'from',
        'like_count' => 'likeCount',
        'reply_count' => 'replyCount',
        'platform' => 'platform',
        'url' => 'url',
        'replies' => 'replies',
        'can_reply' => 'canReply',
        'can_delete' => 'canDelete',
        'can_hide' => 'canHide',
        'can_like' => 'canLike',
        'is_hidden' => 'isHidden',
        'is_liked' => 'isLiked',
        'like_uri' => 'likeUri',
        'cid' => 'cid',
        'parent_id' => 'parentId',
        'root_uri' => 'rootUri',
        'root_cid' => 'rootCid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'message' => 'setMessage',
        'created_time' => 'setCreatedTime',
        'from' => 'setFrom',
        'like_count' => 'setLikeCount',
        'reply_count' => 'setReplyCount',
        'platform' => 'setPlatform',
        'url' => 'setUrl',
        'replies' => 'setReplies',
        'can_reply' => 'setCanReply',
        'can_delete' => 'setCanDelete',
        'can_hide' => 'setCanHide',
        'can_like' => 'setCanLike',
        'is_hidden' => 'setIsHidden',
        'is_liked' => 'setIsLiked',
        'like_uri' => 'setLikeUri',
        'cid' => 'setCid',
        'parent_id' => 'setParentId',
        'root_uri' => 'setRootUri',
        'root_cid' => 'setRootCid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'message' => 'getMessage',
        'created_time' => 'getCreatedTime',
        'from' => 'getFrom',
        'like_count' => 'getLikeCount',
        'reply_count' => 'getReplyCount',
        'platform' => 'getPlatform',
        'url' => 'getUrl',
        'replies' => 'getReplies',
        'can_reply' => 'getCanReply',
        'can_delete' => 'getCanDelete',
        'can_hide' => 'getCanHide',
        'can_like' => 'getCanLike',
        'is_hidden' => 'getIsHidden',
        'is_liked' => 'getIsLiked',
        'like_uri' => 'getLikeUri',
        'cid' => 'getCid',
        'parent_id' => 'getParentId',
        'root_uri' => 'getRootUri',
        'root_cid' => 'getRootCid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('created_time', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('like_count', $data ?? [], null);
        $this->setIfExists('reply_count', $data ?? [], null);
        $this->setIfExists('platform', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('replies', $data ?? [], null);
        $this->setIfExists('can_reply', $data ?? [], null);
        $this->setIfExists('can_delete', $data ?? [], null);
        $this->setIfExists('can_hide', $data ?? [], null);
        $this->setIfExists('can_like', $data ?? [], null);
        $this->setIfExists('is_hidden', $data ?? [], null);
        $this->setIfExists('is_liked', $data ?? [], null);
        $this->setIfExists('like_uri', $data ?? [], null);
        $this->setIfExists('cid', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('root_uri', $data ?? [], null);
        $this->setIfExists('root_cid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets created_time
     *
     * @return \DateTime|null
     */
    public function getCreatedTime()
    {
        return $this->container['created_time'];
    }

    /**
     * Sets created_time
     *
     * @param \DateTime|null $created_time created_time
     *
     * @return self
     */
    public function setCreatedTime($created_time)
    {
        if (is_null($created_time)) {
            throw new \InvalidArgumentException('non-nullable created_time cannot be null');
        }
        $this->container['created_time'] = $created_time;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \Late\Model\GetInboxPostComments200ResponseCommentsInnerFrom|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \Late\Model\GetInboxPostComments200ResponseCommentsInnerFrom|null $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets like_count
     *
     * @return int|null
     */
    public function getLikeCount()
    {
        return $this->container['like_count'];
    }

    /**
     * Sets like_count
     *
     * @param int|null $like_count like_count
     *
     * @return self
     */
    public function setLikeCount($like_count)
    {
        if (is_null($like_count)) {
            throw new \InvalidArgumentException('non-nullable like_count cannot be null');
        }
        $this->container['like_count'] = $like_count;

        return $this;
    }

    /**
     * Gets reply_count
     *
     * @return int|null
     */
    public function getReplyCount()
    {
        return $this->container['reply_count'];
    }

    /**
     * Sets reply_count
     *
     * @param int|null $reply_count reply_count
     *
     * @return self
     */
    public function setReplyCount($reply_count)
    {
        if (is_null($reply_count)) {
            throw new \InvalidArgumentException('non-nullable reply_count cannot be null');
        }
        $this->container['reply_count'] = $reply_count;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string|null
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string|null $platform The platform this comment is from
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        if (is_null($platform)) {
            throw new \InvalidArgumentException('non-nullable platform cannot be null');
        }
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url Direct link to the comment on the platform (if available)
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets replies
     *
     * @return object[]|null
     */
    public function getReplies()
    {
        return $this->container['replies'];
    }

    /**
     * Sets replies
     *
     * @param object[]|null $replies replies
     *
     * @return self
     */
    public function setReplies($replies)
    {
        if (is_null($replies)) {
            throw new \InvalidArgumentException('non-nullable replies cannot be null');
        }
        $this->container['replies'] = $replies;

        return $this;
    }

    /**
     * Gets can_reply
     *
     * @return bool|null
     */
    public function getCanReply()
    {
        return $this->container['can_reply'];
    }

    /**
     * Sets can_reply
     *
     * @param bool|null $can_reply can_reply
     *
     * @return self
     */
    public function setCanReply($can_reply)
    {
        if (is_null($can_reply)) {
            throw new \InvalidArgumentException('non-nullable can_reply cannot be null');
        }
        $this->container['can_reply'] = $can_reply;

        return $this;
    }

    /**
     * Gets can_delete
     *
     * @return bool|null
     */
    public function getCanDelete()
    {
        return $this->container['can_delete'];
    }

    /**
     * Sets can_delete
     *
     * @param bool|null $can_delete can_delete
     *
     * @return self
     */
    public function setCanDelete($can_delete)
    {
        if (is_null($can_delete)) {
            throw new \InvalidArgumentException('non-nullable can_delete cannot be null');
        }
        $this->container['can_delete'] = $can_delete;

        return $this;
    }

    /**
     * Gets can_hide
     *
     * @return bool|null
     */
    public function getCanHide()
    {
        return $this->container['can_hide'];
    }

    /**
     * Sets can_hide
     *
     * @param bool|null $can_hide Whether this comment can be hidden (Facebook
     *
     * @return self
     */
    public function setCanHide($can_hide)
    {
        if (is_null($can_hide)) {
            throw new \InvalidArgumentException('non-nullable can_hide cannot be null');
        }
        $this->container['can_hide'] = $can_hide;

        return $this;
    }

    /**
     * Gets can_like
     *
     * @return bool|null
     */
    public function getCanLike()
    {
        return $this->container['can_like'];
    }

    /**
     * Sets can_like
     *
     * @param bool|null $can_like Whether this comment can be liked (Facebook
     *
     * @return self
     */
    public function setCanLike($can_like)
    {
        if (is_null($can_like)) {
            throw new \InvalidArgumentException('non-nullable can_like cannot be null');
        }
        $this->container['can_like'] = $can_like;

        return $this;
    }

    /**
     * Gets is_hidden
     *
     * @return bool|null
     */
    public function getIsHidden()
    {
        return $this->container['is_hidden'];
    }

    /**
     * Sets is_hidden
     *
     * @param bool|null $is_hidden Whether the comment is currently hidden
     *
     * @return self
     */
    public function setIsHidden($is_hidden)
    {
        if (is_null($is_hidden)) {
            throw new \InvalidArgumentException('non-nullable is_hidden cannot be null');
        }
        $this->container['is_hidden'] = $is_hidden;

        return $this;
    }

    /**
     * Gets is_liked
     *
     * @return bool|null
     */
    public function getIsLiked()
    {
        return $this->container['is_liked'];
    }

    /**
     * Sets is_liked
     *
     * @param bool|null $is_liked Whether the current user has liked this comment
     *
     * @return self
     */
    public function setIsLiked($is_liked)
    {
        if (is_null($is_liked)) {
            throw new \InvalidArgumentException('non-nullable is_liked cannot be null');
        }
        $this->container['is_liked'] = $is_liked;

        return $this;
    }

    /**
     * Gets like_uri
     *
     * @return string|null
     */
    public function getLikeUri()
    {
        return $this->container['like_uri'];
    }

    /**
     * Sets like_uri
     *
     * @param string|null $like_uri Bluesky like URI for unliking
     *
     * @return self
     */
    public function setLikeUri($like_uri)
    {
        if (is_null($like_uri)) {
            throw new \InvalidArgumentException('non-nullable like_uri cannot be null');
        }
        $this->container['like_uri'] = $like_uri;

        return $this;
    }

    /**
     * Gets cid
     *
     * @return string|null
     */
    public function getCid()
    {
        return $this->container['cid'];
    }

    /**
     * Sets cid
     *
     * @param string|null $cid Bluesky content identifier
     *
     * @return self
     */
    public function setCid($cid)
    {
        if (is_null($cid)) {
            throw new \InvalidArgumentException('non-nullable cid cannot be null');
        }
        $this->container['cid'] = $cid;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return string|null
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param string|null $parent_id Parent comment ID for nested replies
     *
     * @return self
     */
    public function setParentId($parent_id)
    {
        if (is_null($parent_id)) {
            throw new \InvalidArgumentException('non-nullable parent_id cannot be null');
        }
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets root_uri
     *
     * @return string|null
     */
    public function getRootUri()
    {
        return $this->container['root_uri'];
    }

    /**
     * Sets root_uri
     *
     * @param string|null $root_uri Bluesky root post URI
     *
     * @return self
     */
    public function setRootUri($root_uri)
    {
        if (is_null($root_uri)) {
            throw new \InvalidArgumentException('non-nullable root_uri cannot be null');
        }
        $this->container['root_uri'] = $root_uri;

        return $this;
    }

    /**
     * Gets root_cid
     *
     * @return string|null
     */
    public function getRootCid()
    {
        return $this->container['root_cid'];
    }

    /**
     * Sets root_cid
     *
     * @param string|null $root_cid Bluesky root post CID
     *
     * @return self
     */
    public function setRootCid($root_cid)
    {
        if (is_null($root_cid)) {
            throw new \InvalidArgumentException('non-nullable root_cid cannot be null');
        }
        $this->container['root_cid'] = $root_cid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


