<?php
/**
 * GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.
 *
 * The version of the OpenAPI document: 1.100.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zernio\Model;

use \ArrayAccess;
use \Zernio\ObjectSerializer;

/**
 * GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics Class Doc Comment
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getTikTokSmartPlusMaterialReport_200_response_rows_inner_metrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'spend' => 'float',
        'impressions' => 'float',
        'clicks' => 'float',
        'cpc' => 'float',
        'add_to_cart' => 'float',
        'initiate_checkout' => 'float',
        'add_payment_info' => 'float',
        'purchases' => 'float',
        'purchase_value' => 'float',
        'roas' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'spend' => null,
        'impressions' => null,
        'clicks' => null,
        'cpc' => null,
        'add_to_cart' => null,
        'initiate_checkout' => null,
        'add_payment_info' => null,
        'purchases' => null,
        'purchase_value' => null,
        'roas' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'spend' => true,
        'impressions' => true,
        'clicks' => true,
        'cpc' => true,
        'add_to_cart' => true,
        'initiate_checkout' => true,
        'add_payment_info' => true,
        'purchases' => true,
        'purchase_value' => true,
        'roas' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'spend' => 'spend',
        'impressions' => 'impressions',
        'clicks' => 'clicks',
        'cpc' => 'cpc',
        'add_to_cart' => 'addToCart',
        'initiate_checkout' => 'initiateCheckout',
        'add_payment_info' => 'addPaymentInfo',
        'purchases' => 'purchases',
        'purchase_value' => 'purchaseValue',
        'roas' => 'roas'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'spend' => 'setSpend',
        'impressions' => 'setImpressions',
        'clicks' => 'setClicks',
        'cpc' => 'setCpc',
        'add_to_cart' => 'setAddToCart',
        'initiate_checkout' => 'setInitiateCheckout',
        'add_payment_info' => 'setAddPaymentInfo',
        'purchases' => 'setPurchases',
        'purchase_value' => 'setPurchaseValue',
        'roas' => 'setRoas'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'spend' => 'getSpend',
        'impressions' => 'getImpressions',
        'clicks' => 'getClicks',
        'cpc' => 'getCpc',
        'add_to_cart' => 'getAddToCart',
        'initiate_checkout' => 'getInitiateCheckout',
        'add_payment_info' => 'getAddPaymentInfo',
        'purchases' => 'getPurchases',
        'purchase_value' => 'getPurchaseValue',
        'roas' => 'getRoas'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('spend', $data ?? [], null);
        $this->setIfExists('impressions', $data ?? [], null);
        $this->setIfExists('clicks', $data ?? [], null);
        $this->setIfExists('cpc', $data ?? [], null);
        $this->setIfExists('add_to_cart', $data ?? [], null);
        $this->setIfExists('initiate_checkout', $data ?? [], null);
        $this->setIfExists('add_payment_info', $data ?? [], null);
        $this->setIfExists('purchases', $data ?? [], null);
        $this->setIfExists('purchase_value', $data ?? [], null);
        $this->setIfExists('roas', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets spend
     *
     * @return float|null
     */
    public function getSpend()
    {
        return $this->container['spend'];
    }

    /**
     * Sets spend
     *
     * @param float|null $spend spend
     *
     * @return self
     */
    public function setSpend($spend)
    {
        if (is_null($spend)) {
            array_push($this->openAPINullablesSetToNull, 'spend');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spend', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spend'] = $spend;

        return $this;
    }

    /**
     * Gets impressions
     *
     * @return float|null
     */
    public function getImpressions()
    {
        return $this->container['impressions'];
    }

    /**
     * Sets impressions
     *
     * @param float|null $impressions impressions
     *
     * @return self
     */
    public function setImpressions($impressions)
    {
        if (is_null($impressions)) {
            array_push($this->openAPINullablesSetToNull, 'impressions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('impressions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['impressions'] = $impressions;

        return $this;
    }

    /**
     * Gets clicks
     *
     * @return float|null
     */
    public function getClicks()
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     *
     * @param float|null $clicks clicks
     *
     * @return self
     */
    public function setClicks($clicks)
    {
        if (is_null($clicks)) {
            array_push($this->openAPINullablesSetToNull, 'clicks');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('clicks', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['clicks'] = $clicks;

        return $this;
    }

    /**
     * Gets cpc
     *
     * @return float|null
     */
    public function getCpc()
    {
        return $this->container['cpc'];
    }

    /**
     * Sets cpc
     *
     * @param float|null $cpc cpc
     *
     * @return self
     */
    public function setCpc($cpc)
    {
        if (is_null($cpc)) {
            array_push($this->openAPINullablesSetToNull, 'cpc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cpc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cpc'] = $cpc;

        return $this;
    }

    /**
     * Gets add_to_cart
     *
     * @return float|null
     */
    public function getAddToCart()
    {
        return $this->container['add_to_cart'];
    }

    /**
     * Sets add_to_cart
     *
     * @param float|null $add_to_cart add_to_cart
     *
     * @return self
     */
    public function setAddToCart($add_to_cart)
    {
        if (is_null($add_to_cart)) {
            array_push($this->openAPINullablesSetToNull, 'add_to_cart');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('add_to_cart', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['add_to_cart'] = $add_to_cart;

        return $this;
    }

    /**
     * Gets initiate_checkout
     *
     * @return float|null
     */
    public function getInitiateCheckout()
    {
        return $this->container['initiate_checkout'];
    }

    /**
     * Sets initiate_checkout
     *
     * @param float|null $initiate_checkout initiate_checkout
     *
     * @return self
     */
    public function setInitiateCheckout($initiate_checkout)
    {
        if (is_null($initiate_checkout)) {
            array_push($this->openAPINullablesSetToNull, 'initiate_checkout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('initiate_checkout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['initiate_checkout'] = $initiate_checkout;

        return $this;
    }

    /**
     * Gets add_payment_info
     *
     * @return float|null
     */
    public function getAddPaymentInfo()
    {
        return $this->container['add_payment_info'];
    }

    /**
     * Sets add_payment_info
     *
     * @param float|null $add_payment_info add_payment_info
     *
     * @return self
     */
    public function setAddPaymentInfo($add_payment_info)
    {
        if (is_null($add_payment_info)) {
            array_push($this->openAPINullablesSetToNull, 'add_payment_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('add_payment_info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['add_payment_info'] = $add_payment_info;

        return $this;
    }

    /**
     * Gets purchases
     *
     * @return float|null
     */
    public function getPurchases()
    {
        return $this->container['purchases'];
    }

    /**
     * Sets purchases
     *
     * @param float|null $purchases purchases
     *
     * @return self
     */
    public function setPurchases($purchases)
    {
        if (is_null($purchases)) {
            array_push($this->openAPINullablesSetToNull, 'purchases');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchases', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchases'] = $purchases;

        return $this;
    }

    /**
     * Gets purchase_value
     *
     * @return float|null
     */
    public function getPurchaseValue()
    {
        return $this->container['purchase_value'];
    }

    /**
     * Sets purchase_value
     *
     * @param float|null $purchase_value purchase_value
     *
     * @return self
     */
    public function setPurchaseValue($purchase_value)
    {
        if (is_null($purchase_value)) {
            array_push($this->openAPINullablesSetToNull, 'purchase_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchase_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchase_value'] = $purchase_value;

        return $this;
    }

    /**
     * Gets roas
     *
     * @return float|null
     */
    public function getRoas()
    {
        return $this->container['roas'];
    }

    /**
     * Sets roas
     *
     * @param float|null $roas roas
     *
     * @return self
     */
    public function setRoas($roas)
    {
        if (is_null($roas)) {
            array_push($this->openAPINullablesSetToNull, 'roas');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('roas', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['roas'] = $roas;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


