<?php
/**
 * GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetricsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.64.0
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetricsTest Class Doc Comment
 *
 * @category    Class
 * @description GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetricsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics"
     */
    public function testGetTikTokSmartPlusMaterialReport200ResponseRowsInnerMetrics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spend"
     */
    public function testPropertySpend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "impressions"
     */
    public function testPropertyImpressions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clicks"
     */
    public function testPropertyClicks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cpc"
     */
    public function testPropertyCpc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "add_to_cart"
     */
    public function testPropertyAddToCart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "initiate_checkout"
     */
    public function testPropertyInitiateCheckout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "add_payment_info"
     */
    public function testPropertyAddPaymentInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchases"
     */
    public function testPropertyPurchases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchase_value"
     */
    public function testPropertyPurchaseValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "roas"
     */
    public function testPropertyRoas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
